### ISSUE TITLE
¿Qué es una época?

### ISSUE THREAD

**Issue by Christianlr** [adelahera/basket-stats#11]
Las épocas definen un periódo concreto, en este caso, dentro de la historia del baloncesto. Una época no está vacía, es decir, recoge una serie de jugadores. Por lo tanto nos servirá para agruparlos según se quiera y poder tratar cada uno de los datos que estos presentan.

**Comment by JJ** [comment]
¿Estás confundiendo "época" con "etapa"?

**Comment by JJ** [comment]
Tampoco puedes decidir en el mismo issue de qué se va a tratar, si un objeto valor o una entidad. Ni, para el caso, dedicir que va a haber una estructura llamada "etapa" (o época). Lo que dice la HU es que el periodista necesita ser capaz de comparar valores de diferentes épocas, por lo que lo que habría que hacer es entender qué hay que comparar y qué procesamiento hay que hacer para que sean comparables, creo yo.
