### ISSUE TITLE
Elección del lenguaje de programación

### ISSUE THREAD

**Issue by Christianlr** [adelahera/basket-stats#6]
Buenas @adelahera! Me han asignado tu proyecto para determinar qué lenguaje de programación vas a usar. Considero interesantes lenguajes como `JavaScript`, `TypeScript` o `Go`. Si por casualidad tienes en mente otro lenguaje para el desarrollo del proyecto, házmelo saber :ok_hand:

**Comment by adelahera** [comment]
Buenas! Yo había pensado que, por el tipo de problema que voy a resolver, Go es la mejor opción, pues uno de sus puntos fuertes es que es muy eficiente y da muy buen rendimiento al trabajar con una gran cantidad de datos,.
