### ISSUE TITLE
Idea para la estructura de datos

### ISSUE THREAD

**Issue by Christianlr** [adelahera/basket-stats#8]
Buenas @adelahera! Voy a comentarte un poco la estructura que he pensado para resolver el problema que se describe en base a las historias de usuario 😎.

Lo primero que quiero destacar de este problema es que puede tener un enfoque bastante personal y la solución que propongo podría no ser la definitiva o la más conveniente. Por lo tanto, espero que me des tu opinión al respecto y podamos llegar a la mejor solución posible 😄. 

Ahora si, te comento un poco las clases que de primeras he considerado para su resolución. Partimos de dos objetos valor y terminamos con una entidad (esto puede ser erróneo, ya que debemos de tener en cuenta si los datos con los que trabajamos van a cambiar en el tiempo o son inmutables).

# Estructura para el problema
### Clase Jugador

En esta clase jugador, vamos a recoger aquellos datos que se comentan de los jugadores. Por lo tanto, contendrá variables para recoger cada uno de los datos necesarios de los jugadores. Además, se comenta que se dispone de datos en la web para completar esto. Sería interesante conocer todos los campos en profundidad para poder completar o crear la clase correctamente sin dejar ningún datos atrás. Pero parto de aquellos parámetros que se mencionan tanto en el problema en general como en la HU.

### Clase Etapa

Como uno de los puntos que más se menciona es la comparación de jugadores por etapas, vamos a crear etapas como tal. En base a una fecha inicio y fecha final se creará un `map` que contendrá partiendo del campo de intervalo de tiempo, un array de jugadores con todos y cada uno de estos jugadores que se comprenden en la etapa. Esto para poder compararlos posteriormente.

### Clase Estadistica

Necesitamos una clase como mínimo donde se contenga la lógica de negocio que estamos buscando, y es aquella en la que se realizan las comparaciones que se plantean para el problema. Esta clase deberá contener aquellas etapas definidas previamente con los jugadores que también previamente se han creado. 

### Comentarios y algunas curiosidades

Voy a recoger en este issue la idea general de la estructura para el problema. Me gustaría de nuevo comentar que este quizás no es el enfoque que buscabas pero estamos aquí para  poder encontrarlo. 

Como mencionas en el concepto del problema, me llama la atención el hecho de tener en cuenta el tipo de reglas de la etapa, y realmente me gustaría que me comentaras un poco sobre esto para ver si realmente debemos de darle un giro a la estructura propuesta. Lo que si que he hecho es basarme más en la etapa que en las reglas, de ahí la consideración de crear una clase así.

### Otras clases que pueden ser interesantes

Por último y como te he mencionado antes, es un problema que puede tener diversas soluciones y pueden ser correctas más de una. Como última consideración y, a mi parecer, como buen aporte, es la creación de clases como `Equipo` o `Temporada`. Podrían ser una buena idea siguiendo el comportamiento de la clase `Etapa` mencionada anteriormente, para una mayor claridad y posibilidades en la comparación de estadísticas. 
Ya me comentas que te parece y a ver si podemos dar con la mejor manera para resolver el problema!👍😄

**Comment by adelahera** [comment]
Como ya hemos hablado, lo veo todo bastante bien. Las clases `Jugador`, `Etapa` y `Estadística` son las que había pensado para comenzar el problema. Lo de las reglas, lo que hemos hablado, al estar implícitas dentro de las propias estadísticas, creo que no haría falta implementar una clase como tal. Sobre el equipo y temporada, al no haberlo puesto explícitamente en las historias de usuario, tampoco las crearía, al menos de momento. Quizá, en la clase jugador, se podría crear un `map`, donde se guarde el equipo donde jugó en una temporada específica.
